[workspace]
members = ["core", "cli", "tests/e2e"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
git_mile_core = { path = "core" }

[patch.crates-io]
indexmap = { git = "https://github.com/indexmap-rs/indexmap", tag = "2.6.0" }
