msrv = "1.90"
doc-valid-idents = ["UUID"]
allowed-duplicate-crates = [
    "crossterm",
    "darling",
    "darling_core",
    "darling_macro",
    "linux-raw-sys",
    "mio",
    "rustix",
    "thiserror",
    "thiserror-impl",
    "unicode-width",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
