[package]
name = "git-mile"
version.workspace = true
edition.workspace = true

[dependencies]
git_mile_core.workspace = true
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[dev-dependencies]
git2 = { version = "0.19", features = ["vendored-openssl"] }
tempfile = "3.10"
