[alias]
fmt-all = "fmt --all"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"
lint-pedantic = "clippy --workspace --all-targets --all-features -- --cap-lints=warn -W clippy::pedantic -W clippy::nursery -W clippy::cargo"
test-all = "test --workspace"

[build]
rustflags = ["-Dwarnings"]
