[workflow]
states = [
  { value = "state/todo", label = "Todo", kind = "todo" },
  { value = "state/in-progress", label = "In Progress", kind = "in_progress" },
  { value = "state/done", label = "Done", kind = "done" }
]
